### ISSUE TITLE
[Suggestion] Toggle configsetting for voiding

### ISSUE THREAD

**Issue by HRZNzero** [Sefiraat/DankTech#10]
Please integrate a feature to toggle it, so that dankpacks do not automaticaly void items if filled but instead just leave them be as is and instead notify the player that its full.

In our testing we found it an issue that players could potentialy grief others by walking around dropzones and collect drops and destroy them.

**Comment by Sefiraat** [comment]
I'm not sure how I feel about this suggestion. I have added it to my todo list and will think on it more.

**Comment by Sefiraat** [comment]
After more though and discussing with other server owners I feel this setting just isn't worth while. It may make sense for T1 or T2 but as soon as you get to higher levels it becomes a bit redundant. So i think i'll bench this for now.
