### ISSUE TITLE
DankTech fails to start

### ISSUE THREAD

**Issue by Apeiros-46B** [Sefiraat/DankTech#12]
## Starting the server and waiting for DankTech to load results in an error
Step 1: Start the server
Step 2: Look for the error

## Log of error, if applicable
![image](https://user-images.githubusercontent.com/61390942/120932672-95364080-c6ab-11eb-8acb-82c3e25d37a4.png)

## Server Type and version (Spigot/Paper etc.)
![image](https://user-images.githubusercontent.com/61390942/120932185-a5e5b700-c6a9-11eb-80ff-de4a661acf92.png)
Server software: Purpur 1.16.5 build 1157 (paper fork)
Java environment: Java 14
Operating system: Pop OS 20.10

## Minecraft version
1.16.5

**Comment by Sefiraat** [comment]
Heya Apeiros, can you download the pre-release jar 1.7.2-SNAPSHOT and let me know if this sorts the issue for you? 
Sorry for this :)

**Comment by Apeiros-46B** [comment]
I used the pre-release jar and it works normally now. Thanks for the quick response!

**Comment by Sefiraat** [comment]
Anytime, ill ship a proper release asap and you can stick to the pre or update :)
