### ISSUE TITLE
[Issue] Wrong crafting pattern creates default player head

### ISSUE THREAD

**Issue by 0swin** [Sefiraat/DankTech#16]
## Description (Mandatory)
Wrong crafting pattern creates default player head

## What caused the issue, what steps led up to the issue (Mandatory)
Trying to create a Trash Pack with a wrong recipe creates a player head : example using a Trash Pack t2 with Storage Cells t1 around it
![Screenshot 2021-07-16 160653](https://user-images.githubusercontent.com/10211651/125960807-9cb70e01-7321-4918-a370-84f3baa66151.png)

## Log of error, if applicable
No logs

## Server Type and verison (Spigot/Paper etc.)
paper-1.17.1-107.jar
Plugins (34): AutomatedCrafting, Brewery, ChestTerminal, ColoredEnderChests, CrazyEnchantments, DankTech, DriveBackupV2, DyedBackpacks, DynaTech, dynmap, EcoPower, EquivalencyTech, ExperienceTome, FastLeafDecay, FluffyMachines, GSit, LiteXpansion, LuckPerms, MendingEnchant, Multiverse-Core, ProtocolLib, SetHomes, SFCalc, SimpleStorage, SimpleUtils, SkinsRestorer, Slimefun, SlimefunOreChunks, SlimeTinker, SlimyTreeTaps, SoundMuffler, SpawnerSilk, ViaBackwards, ViaVersion

## Minecraft version
1.17.1

**Comment by Sefiraat** [comment]
Thanks for the info, ill check this out!
