### ISSUE TITLE
trash pack vanishes

### ISSUE THREAD

**Issue by jigglypuff2731** [Sefiraat/DankTech#17]
## Description (Mandatory)
when i craft dank trash pack and open it the pack vanishes 
## What caused the issue, what steps led up to the issue (Mandatory)

crafted a dank trash pack and opened it 
## Log of error, if applicable
[Sun, 8. Aug 2021 09:02:40 UTC ERROR] Could not pass event PlayerInteractEvent to DankTech v1.2.8
i know you said there should be more but this was all there was 
## Server Type and verison (Spigot/Paper etc.)
purpur
## Minecraft version
1.17.1

**Comment by Sefiraat** [comment]
While I still need more detail as discussed on Discord, I notice that 1.2.8 is not the most recent version so your server will need upgrade and re-test and then provide the error messages if applicable at that point.

Cheers.

**Comment by Sefiraat** [comment]
With no further comment, ill close this for now :)
