### ISSUE TITLE
Update to Slimefun RC28

### ISSUE THREAD

**Issue by DexterSK** [Sefiraat/DankTech#18]
## Description (Mandatory)
Update to Slimefun RC28 please, thanks
## Server Type and verison (Spigot/Paper etc.)
purpur latest
## Minecraft version
1.17.1

**Comment by Sefiraat** [comment]
Slimefun 27 was the breaking changes update and there is already a release out for that tested and working a-ok.

**Comment by Sefiraat** [comment]
It's been pointed out that I uploaded the wrong file into the release which may be the issue you had here, if so sorry and the new one is now correct!

**Comment by DexterSK** [comment]
yeah working fine now, thank you master!
