### ISSUE TITLE
Items not being picked up by Dank when Inventory is full

### ISSUE THREAD

**Issue by Bunnky** [Sefiraat/DankTech#2]
Basically title. If your inventory is full, dank will not pickup items registered to it.

Tested with T9, not sure about others, i presume the logic is the same.

Reported by: oah

**Comment by Sefiraat** [comment]
This is Triggered by EntityPickupItemEvent which only fires when the item can and then is picked up. The workaround would be to contantly scan an area around all players and check danks/slots and item to be picked up to see if it can be absorbed. The performace overhead would be to high for the convenience 😢
