### ISSUE TITLE
no limit...

### ISSUE THREAD

**Issue by Yukylyu** [Sefiraat/DankTech#30]
## Description (Mandatory)

Hi, I have found a bug with the dankpacks, there is an item limit for example the t5 the maximum is 8192. If the player picks up the item on the ground the plugin will block the pickup so perfect, but on the other hand if he adds him even items with shift + left click he can add items to infinity despite the limit. Thank you in advance for your help.

## Log of error, if applicable
no error

## Server Type and verison (Spigot/Paper etc.)
paper 1.18
DankTech-1.2.11

## Minecraft version
1.18

**Comment by Yukylyu** [comment]
Hi could you fix this problem please? :(

**Comment by Sefiraat** [comment]
Heya, DankTech Is no longer supported and it’s been superseded with DankTech2 which does not have this issue.
