### ISSUE TITLE
[Suggestion] permissions / blacklist / translation

### ISSUE THREAD

**Issue by Yukylyu** [Sefiraat/DankTech#5]
Hi I like your amazing plugin ! Could you add a blacklist for item (and world) or add a permissions to use please ? (I would like to prevent the use in dungeons) and a translation in the config file? ^^

**Comment by Sefiraat** [comment]
Hi Yukylyu,

I have implemented world blacklisting for Item Pickup, BLock placement and Opening Dank/Trash Packs.
OP users and/or users with **danktech.admin** permissions will bypass these restrictions.

Please download release 1.2.1. :)

I have added translation to my todo list for the future.

**Comment by Yukylyu** [comment]
Hi thank you very much for your update, would it be possible to add too a blacklist of items and the possibility of changing the text to put our own translation please ? :)
