### ISSUE TITLE
[Suggestion] blacklist items

### ISSUE THREAD

**Issue by Yukylyu** [Sefiraat/DankTech#6]
Hi
https://zupimages.net/up/21/20/a5yy.png

**Comment by Sefiraat** [comment]
This is in progress now, will ship in 1.2.3 :)

**Comment by Sefiraat** [comment]
Suggestion implemented in 1.2.3 - Items you want blacklisted that are ALREADY inside a dank will NOT be removed and will still pick up items. These need to be manually removed and can be done via /danktech viewpacks if needed.

Let me know what you think and more suggestions are welcome!
