### ISSUE TITLE
[Issue] error

### ISSUE THREAD

**Issue by Yukylyu** [Sefiraat/DankTech#7]
Hi^^
## Description (Mandatory)
The error occurs when I add an item to an empty dankpack, the plugin no longer saves the items.

## Log of error, if applicable
https://pastebin.com/t0VTgLaP

## Server Type and verison (Spigot/Paper etc.)
spigot 
## Minecraft version
1.16.5

**Comment by Sefiraat** [comment]
Hi Yuky,

What level DankPack?
What item are you trying to put in the pack?

Were you using 1.2.2 before upgrading to 1.2.3?

I cannot seem to recreate this in my 1.16.5 server.

**Comment by Yukylyu** [comment]
dankpack t1 (i have try iron_ingot and sweet_berries) version 1.2.3.

version 1.2.2 the plugin work correcly

**Comment by Sefiraat** [comment]
Can you please PasteBin your Dank_Storages.yml and let me know the ID of the pack (this shows in chat when your right click to open).

**Comment by Yukylyu** [comment]
PACKS:
  PACKS_BY_ID:
    '1':
      LEVEL: 1
      SLOT1:
        VOLUME: 0
      LAST_OPENED_BY_UUID: 217864f4-e4f2-4657-b06f-fa4141b5f709
      LAST_OPENED_BY: _Yuky_
      LAST_OPENED_ON: '2021-05-19 16:46:05'

------------------------(version DankTech-1.2.3 )-------------------------------------------

chat => https://zupimages.net/up/21/20/tugl.png
test => https://zupimages.net/up/21/20/e3jf.png

**Comment by Sefiraat** [comment]
Can you let me know your server IP? If you don’t want it on GitHub then DM me on spigot where we have spoken before. If the server is whitelisted, please add IGN Sefiraat to the whitelist

**Comment by Yukylyu** [comment]
this is not an online server just for me at the moment...

And i have reset all files too it's doesn't work

**Comment by Sefiraat** [comment]
Unfortunately I cannot recreate this on any of my test servers which generally means it's a config issue or a conflicting plugin. 
Can you let me know what plugins you have on the server. You might need to try the plugin on it's own first then slowly add plugins until it fails.

**Comment by Sefiraat** [comment]
Whey! I have managed to recreate the bug - working on a fix now!

**Comment by Sefiraat** [comment]
Thank for the report - I have updated the 1.2.3 jar with this fix, redownload and let me know how you get one :D

**Comment by Yukylyu** [comment]
thank you it works !^^
