### ISSUE TITLE
[Suggestion] change name dankpack or full translation?

### ISSUE THREAD

**Issue by Yukylyu** [Sefiraat/DankTech#8]
Hi ^^I know it's in progress but I'm opening a ticket ^^

I would like a possible translation or be able to at least change the name of the dank pack and dank cell so that it fits more into the universe of my server.

thank you :)

**Comment by Sefiraat** [comment]
The name Dank Pack will stay hard coded as this is a throwback to the mod and I want to honour that. I will be adding config options for all other text items and messages. Working on this for the next release :)

**Comment by Sefiraat** [comment]
Hi @Yukylyu please give https://github.com/Sefiraat/DankTech/releases/tag/1.2.6-SNAPSHOT a try. This will be in pre release until I have been able to do more testing, but should be good enough if you would like to test as well.

Let me know if you have any feedback!

**Comment by Sefiraat** [comment]
1.2.6 is now out for all users
